# your projects folder so that we can `c [tab]` to
export PROJECTS="$HOME/Development"

# shortcut to this dotfiles path is $DOTFILES
export DOTFILES="$PROJECTS/dotfiles"

# source the base zshrc configurations first
for config_file (~/.config/zsh/*.zsh) source $config_file

# source the remaining zsh config files
# the `^zsh` bit means all directories _except_ the `zsh` directory
for config_file (~/.config/^zsh/*.zsh) source $config_file

#source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
